# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  bob-benchmarks:
    dependencies:
    - base
    - bob
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: bob is a new Haskeleton package.
executables:
  bob:
    dependencies:
    - base
    - bob
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/bob
library:
  dependencies:
  - base
  - turtle
  - mtl
  - text
  - directory
  source-dirs: library
  default-extensions:
    - OverloadedStrings
    - DuplicateRecordFields
license: MIT
maintainer: Author name here
name: bob
synopsis: A new Haskeleton package.
tests:
  bob-test-suite:
    dependencies:
    - base
    - bob
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
